"""payments

Sprint 11: payments (online checkout + pay at clinic), gateway webhook
audit/idempotency log, and consultation fees per doctor per clinic.

Revision ID: 7b73d61e3365
Revises: 9a41c2e7d3b5
Create Date: 2026-09-19 17:52:21.478150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b73d61e3365'
down_revision: Union[str, None] = '9a41c2e7d3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('card', 'wallet', 'pay_at_clinic', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'expired', 'due_at_clinic', 'refund_pending', 'refunded', 'needs_refund', name='payment_status'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['availability_id'], ['availability.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_order_id')
    )
    op.create_index('ix_payments_patient_id', 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_key', name='uq_payment_events_provider_event')
    )
    op.add_column('clinic_staff', sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_staff', 'consultation_fee')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_patient_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###

    # Enum types outlive their tables in Postgres; see the initial migration.
    op.execute("DROP TYPE IF EXISTS payment_method, payment_status")
