"""clinic hours and slot duration

Adds the clinic's weekly opening hours (`clinic_hours`) and the default
slot length used when generating a doctor's bookable slots from them
(Sprint 13, the clinic admin dashboard).

Revision ID: 83a2477a2dbb
Revises: cde6dcc397f6
Create Date: 2026-09-21 09:23:31.468819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a2477a2dbb'
down_revision: Union[str, None] = 'cde6dcc397f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_hours',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('closes_at > opens_at', name='ck_clinic_hours_closes_after_opens'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_clinic_hours_weekday_range'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'weekday', name='uq_clinic_hours_clinic_weekday')
    )
    op.create_index(op.f('ix_clinic_hours_clinic_id'), 'clinic_hours', ['clinic_id'], unique=False)
    op.add_column('clinics', sa.Column('slot_duration_minutes', sa.Integer(), server_default='30', nullable=False))
    # Table-level CHECKs aren't emitted by autogenerate; added by hand.
    op.create_check_constraint(
        'ck_clinics_slot_duration_minutes_range', 'clinics', 'slot_duration_minutes BETWEEN 5 AND 240'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_clinics_slot_duration_minutes_range', 'clinics', type_='check')
    op.drop_column('clinics', 'slot_duration_minutes')
    op.drop_index(op.f('ix_clinic_hours_clinic_id'), table_name='clinic_hours')
    op.drop_table('clinic_hours')
    # ### end Alembic commands ###
