"""doctor verification

Adds doctor sign-up fields (sub-specialty, licence number, degree,
university, city), the admin's review decision (submitted_at,
reviewed_at, reviewed_by_user_id, verification_notes) and the
`doctor_documents` table holding uploaded verification documents (the
files themselves live under UPLOAD_DIR, never in the database).

Revision ID: cde6dcc397f6
Revises: 7b73d61e3365
Create Date: 2026-09-21 01:30:49.959483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde6dcc397f6'
down_revision: Union[str, None] = '7b73d61e3365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_documents',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('medical_license', 'medical_degree', 'national_id', 'specialty_certificate', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='document_status'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    op.create_index(op.f('ix_doctor_documents_doctor_id'), 'doctor_documents', ['doctor_id'], unique=False)
    op.add_column('doctors', sa.Column('sub_specialty', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('license_number', sa.String(length=128), nullable=True))
    op.add_column('doctors', sa.Column('medical_degree', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('doctors', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('doctors', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_doctors_reviewed_by_user_id_users', 'doctors', 'users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_doctors_reviewed_by_user_id_users', 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'verification_notes')
    op.drop_column('doctors', 'reviewed_by_user_id')
    op.drop_column('doctors', 'reviewed_at')
    op.drop_column('doctors', 'submitted_at')
    op.drop_column('doctors', 'city')
    op.drop_column('doctors', 'university')
    op.drop_column('doctors', 'medical_degree')
    op.drop_column('doctors', 'license_number')
    op.drop_column('doctors', 'sub_specialty')
    op.drop_index(op.f('ix_doctor_documents_doctor_id'), table_name='doctor_documents')
    op.drop_table('doctor_documents')
    # ### end Alembic commands ###

    # Enum types outlive their tables in Postgres; see the initial migration.
    op.execute("DROP TYPE IF EXISTS document_type, document_status")
